{
 "title": "User Monitoring Elastic",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "T001-num-USERS-all",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view001_num_USERS_total;",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "Total number of co-prod processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct id) from coproductionprocess;"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "coproductionprocess_id.keyword",
       "hide": true,
       "id": "1",
       "type": "cardinality"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "action:CREATE AND model:COPRODUCTIONPROCESS",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Interlinkers Deployed (log)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action.keyword:CREATE AND model.keyword:ASSET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T002w_num_TEAMS_USERS3_per_PROCESS",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "select * from grafana.\"Serge_view002w_num_TEAMS_USERS3_per_PROCESS\"",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T003x_num_users2_per_ROLE",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view003x_num_users2_per_ROLE",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T004-num-USERS-per-PROCESS-per-ROLE",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view004_num_USERS_per_PROC_per_ROLE",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T005a-num-ACTIVE-USERS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view005a_num_ACTIVE_USERS_total",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T005b Number of users per co-production process",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "coproductionprocess_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "user_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "NOT _empty_:user_id.keyword",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T005d-num-ACTIVE-USERS-per-PROC-per-ROLE",
   "type": "table",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
   "targets": [
    {
     "queryText": "select * from grafana.\"Serge_view005d_num_ACTIVE_USERS_per_PROC_per_ROLE\"",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T005e Number of active users vs time period",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "coproductionprocess_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "user_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "NOT _empty_:user_id.keyword",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T006-num-USERS-per-TEAM",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view006_num_USERS_per_TEAM",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T007a-num-ACTIVE-USERS-per-PROC-per-TEAM",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view007a_num_ACTIVE_USERS_per_PROC_per_TEAM",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T008a_num_ACTIVE_USERS_per_INTERL_TYPE",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view008a_num_ACTIVE_USERS_per_INTERL_TYPE",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T008b_num_ACTIVE_USERS_per_INTERL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view008b_num_ACTIVE_USERS_per_INTERL",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T009a_num_ACTIVE_USERS_per_INTERL_TYPE_per_PROC",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view009a_num_ACTIVE_USERS_per_INTERL_TYPE_per_PROC",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T009b_num_ACTIVE_USERS_per_INTERL_per_PROC",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 67 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view009b_num_ACTIVE_USERS_per_INTERL_per_PROC",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T010a_num_USERS_per_INTERL_type_per_ROLE",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "queryText": "select * from grafana.\"Serge_view010a_num_USERS_per_INTERL_type_per_ROLE\"",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T010b_num_USERS_per_INTERL_per_ROLE",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 79 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view010b_num_USERS_per_INTERL_per_ROLE",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T011_num_PROCESSES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view011_num_PROCESSES",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T014 Number of co-prod process schema types",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct schema_used)\nfrom coproductionprocess;"
    }
   ]
  },
  {
   "title": "T015_num_PROC_per_SCHEMA",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view015_num_PROC_per_SCHEMA",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T021_num_INTERL_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT count( distinct( id ))\nFROM catalogue.public.interlinker ",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T022a_num_USED_INTERL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view022a_num_USED_INTERL",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T022b_num_USED_INTERL_Internal_Knowledge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 105 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view022b_num_USED_INTERL_Internal_Knowledge",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T022c_num_USED_INTERL_InternalSW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view022c_num_USED_INTERL_InternalSW",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T022d_num_USED_INTERL_ExternalSW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view022d_num_USED_INTERL_ExternalSW",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "Deployed Interlinkers by name",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "softwareinterlinker_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action:CREATE and model:ASSET AND NOT _exists_:knowledgeinterlinker_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T023a Frequency histogram of used Knowledge INTERLINKERs per INT. ID/NAME",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "knowledgeinterlinker_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "action.keyword:CREATE AND model.keyword:ASSET AND (_exists_:knowledgeinterlinker_id.keyword)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T023a_use_frequency_of_INTERL_InternalKnowledge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view023a_use_frequency_of_INTERL_InternalKnowledge",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T023b_use_frequency_of_INTERL_InternalSW",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 135 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view023b_use_frequency_of_INTERL_InternalSW",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T023c_use_frequency_of_INTERL_ExternalSW",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 140 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view023c_use_frequency_of_INTERL_ExternalSW",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T024x_num_USED_INTERL_per_PROC",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 143 },
   "targets": [
    {
     "queryText": "select * from grafana.\"Serge_view024x_num_USED_INTERL_per_PROC\"",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T025_num_USED_INTERL_per_SCHEMA",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 148 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.\"Serge_view025_num_USED_INTERL_per_SCHEMA\"",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T024a Num. used INTERLINKERs (all types) per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "rawSql": "select coproductionprocess_id, count(distinct id)\nfrom asset\ngroup by coproductionprocess_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T024b Num. used Knowledge INTERLINKERs per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "rawSql": "select b.coproductionprocess_id, count(distinct a.id)\nfrom internalasset a\ninner join asset b on (a.id = b.id)\nwhere a.knowledgeinterlinker_id is not null\ngroup by b.coproductionprocess_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T024c Num. used internal SW INTERLINKERs per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "rawSql": "select b.coproductionprocess_id, count(distinct a.id)\nfrom internalasset a\ninner join asset b on (a.id = b.id)\nwhere a.softwareinterlinker_id is not null and a.knowledgeinterlinker_id is null\ngroup by b.coproductionprocess_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T024d Num. used external SW INTERLINKERs per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "rawSql": "select coproductionprocess_id, count(distinct id)\nfrom asset\nwhere type = 'externalasset'\ngroup by coproductionprocess_id;"
    }
   ]
  },
  {
   "title": "T025 Num. used INTERLINKERs per schema TYPE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "targets": [
    {
     "rawSql": "select a.schema_used, count(distinct b.id)\nfrom coproductionprocess a\ninner join asset b on (a.id=b.coproductionprocess_id)\ngroup by a.schema_used\norder by count desc;"
    }
   ]
  },
  {
   "title": "T026_num_USED_INTERL_per_SCHEMA_per_PROC",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 192 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view026_num_USED_INTERL_per_SCHEMA_per_PROC",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T027 INTERLINKER IDs used per co-prod. phase per schema type",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "targets": [
    {
     "rawSql": "select b.phase_id, a.schema_used, count(distinct b.id)\nfrom coproductionprocess a\ninner join asset b on (a.id=b.coproductionprocess_id)\ninner join phase c on (c.id=b.phase_id)\ngroup by b.phase_id, a.schema_used\norder by count desc;"
    }
   ]
  },
  {
   "title": "T031a_Num_Assets_",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 206 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select count( distinct(id) ) as num_Assets from coproduction.public.asset",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T031b_num_ASSETS_for_InterKnow_INTERL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 206 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view031b_num_ASSETS_for_InterKnow_INTERL",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T031c_num_ASSETS_for_InterSW_INTERL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 212 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view031c_num_ASSETS_for_InterSW_INTERL",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T031d_num_ASSETS_for_ExterSW_INTERL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 212 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view031d_num_ASSETS_for_ExterSW_INTERL",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T032x_num_ASSETS_per_PROCESS",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 218 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view032x_num_ASSETS_per_PROCESS",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T033x_num_ASSETS_per_INTERL",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 225 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view033x_num_ASSETS_per_INTERL",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T032a Number of created assets (all INTER types) per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 232 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select coproductionprocess_id, count(distinct id)\nfrom asset\ngroup by coproductionprocess_id\norder by count desc;",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T032b Number of created assets for KNOWLEDGE type INTERL. per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
   "targets": [
    {
     "rawSql": "select a.coproductionprocess_id, count(distinct b.knowledgeinterlinker_id)\nfrom asset a\ninner join internalasset b on (a.id = b.id)\nwhere b.knowledgeinterlinker_id is not null\ngroup by a.coproductionprocess_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T032c Number of created assets for Internal SW type INTERL. per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "targets": [
    {
     "rawSql": "select a.coproductionprocess_id, count(distinct b.softwareinterlinker_id)\nfrom asset a\ninner join internalasset b on (a.id = b.id)\nwhere b.knowledgeinterlinker_id is null\ngroup by a.coproductionprocess_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T032d Number of created assets for External SW type INTERL. per co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
   "targets": [
    {
     "rawSql": "select a.coproductionprocess_id, count(distinct b.id)\nfrom asset a\ninner join externalasset b on (a.id = b.id)\ngroup by a.coproductionprocess_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T033b Number of created assets per Cat_ID/Name of INTERLINKER",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
   "targets": [
    {
     "rawSql": "select knowledgeinterlinker_id, count(id)\nfrom internalasset\nwhere knowledgeinterlinker_id is not null\ngroup by knowledgeinterlinker_id\norder by count desc;\n"
    }
   ]
  },
  {
   "title": "T033c Number of created assets per Cat_ID/Name of INTERLINKER",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
   "targets": [
    {
     "rawSql": "select softwareinterlinker_id, count(id)\nfrom internalasset\nwhere knowledgeinterlinker_id is null\ngroup by softwareinterlinker_id\norder by count desc;\n"
    }
   ]
  },
  {
   "title": "T033d Number of created assets per Cat_ID/Name of INTERLINKER",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
   "targets": [
    {
     "rawSql": "select uri, count(distinct id)\nfrom externalasset\ngroup by uri\norder by count desc;\n"
    }
   ]
  },
  {
   "title": "T034 Number of created assets per user_ID",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 289 },
   "targets": [
    {
     "rawSql": "select creator_id, count(distinct id)\nfrom asset\ngroup by creator_id\norder by count desc;"
    }
   ]
  },
  {
   "title": "T034_Num_Assets_per_USER_",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 298 },
   "targets": [
    {
     "queryTimeout": 60,
     "rawSql": "select u.full_name, -- a.creator_id as user_id, \n       count(distinct a.id) as num_assets\nfrom asset a\nleft join \"user\" u on u.id = a.creator_id\ngroup by u.full_name\norder by num_assets desc\n",
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T035 Number of created assets vs. time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "action.keyword:CREATE AND model.keyword:ASSET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T036 Number of all operations on any asset (C.R.U.D.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 313 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "model.keyword:ASSET AND action.keyword:GET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T037 Number of asset operations per co-prod process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "coproductionprocess_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "model.keyword:ASSET AND action.keyword:GET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T038 Number of asset operations per TYPE / Cat_ID of INTERLINKER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 329 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "model.keyword:ASSET AND action.keyword:GET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T039 Number of asset operations per user_ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "model.keyword:ASSET AND action.keyword:GET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T040 Number of asset operations vs. time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 345 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      },
      { "field": "1", "id": "3", "pipelineAgg": "1", "type": "cumulative_sum" }
     ],
     "query": "model.keyword:ASSET AND action.keyword:GET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T051 Number of users participating in more than one co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 353 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "2", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "coproductionprocess_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "action:GET AND model:ASSET",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T052 Number of INTERLINKERs used in more than one co-prod. process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 361 },
   "targets": [
    {
     "rawSql": "select id, count(coproductionprocess_id)\nfrom asset\ngroup by id\nhaving count(coproductionprocess_id) > 1;\n"
    }
   ]
  },
  {
   "title": "T053_Number_of_TEAMS_",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 369 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select count( distinct(id) ) from coproduction.public.team",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T054 Number of teams per coprod process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 373 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select coproductionprocess_id, count(distinct team_id)\nfrom permission\ngroup by coproductionprocess_id\norder by count desc;",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T055 Number of teams per role (team type)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 381 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select type, count(id) \nfrom team\ngroup by type\norder by count desc;",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T056 Number of team types (roles) within web portal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 389 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "rawSql": "select count(distinct type)\nfrom team\norder by count desc;",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "T057 Number of organizations in web portal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 393 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct id)\nfrom  organization;"
    }
   ]
  },
  {
   "title": "T058_num_USERS_per_ORG",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 397 },
   "targets": [
    {
     "queryText": "select * from grafana.Serge_view058_num_USERS_per_ORG",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  },
  {
   "title": "T058_Num_Organizations_",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "select count(distinct(id)) as num_org from coproduction.public.organization",
     "queryTimeout": 60,
     "timeCol": "time_col"
    }
   ]
  }
 ]
}